name: release

on:
  push:
    tags: ["*"]

jobs:
  create-release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch full history for goreleaser changelog

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.5.0
        with:
          version: latest
          args: release --rm-dist --config deploy/.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update new outdated version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.46
        with:
          krew_template_file: deploy/krew/outdated.yaml
